[2019-10-04 15:35:23] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-04 15:35:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-04 15:35:23] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-04 15:35:23] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-04 16:54:23] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-04 16:54:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-04 16:54:23] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-04 16:54:23] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:35:37] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:35:37] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:35:39] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:35:39] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:44:32] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:44:32] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:44:32] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:44:32] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:40] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:46:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:46:40] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:40] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:48] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:46:48] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:46:48] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:48] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:50] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:46:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:46:50] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:50] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:50] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:46:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:46:50] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:50] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:51] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:46:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:46:51] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:51] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:52] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:46:52] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:46:52] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:52] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:52] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:46:52] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:46:52] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:52] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:53] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:46:53] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:46:53] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:53] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:53] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:46:53] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:46:53] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:46:53] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:47:10] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 03:47:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 03:47:10] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 03:47:10] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 04:40:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 138 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:138, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-10-05 04:40:40] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8888/")" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 138 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8888/\") at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:138, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-10-05 04:40:48] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8888/api/login_check","method":"POST"} []
[2019-10-05 04:40:48] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 04:40:48] php.CRITICAL: Return value of App\Entity\User::getId() must be of the type integer, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 04:40:48] request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of App\Entity\User::getId() must be of the type integer, null returned" at /var/www/symfony/src/Entity/User.php line 34 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Entity\\User::getId() must be of the type integer, null returned at /var/www/symfony/src/Entity/User.php:34)"} []
[2019-10-05 04:57:56] console.ERROR: Error thrown while running command "doctrine:schema:update --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.18.0.3' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.18.0.3' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.18.0.3' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.18.0.3' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:schema:update --force","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.18.0.3' (using password: YES)"} []
[2019-10-05 04:57:56] console.DEBUG: Command "doctrine:schema:update --force" exited with code "1" {"command":"doctrine:schema:update --force","code":1} []
[2019-10-05 04:58:21] console.DEBUG: Command "doctrine:database:drop --force" exited with code "1" {"command":"doctrine:database:drop --force","code":1} []
[2019-10-05 05:26:58] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known"} []
[2019-10-05 05:26:58] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-10-05 05:27:13] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known"} []
[2019-10-05 05:27:13] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-10-05 05:38:04] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known"} []
[2019-10-05 05:38:04] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-10-05 05:59:25] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES)"} []
[2019-10-05 05:59:25] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-10-05 06:01:44] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES)"} []
[2019-10-05 06:01:44] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-10-05 06:01:46] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.20.0.2' (using password: YES)"} []
[2019-10-05 06:01:46] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-10-05 06:01:58] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-10-05 06:04:46] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-10-05 06:04:46] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-10-05 06:04:46] doctrine.DEBUG: CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB [] []
[2019-10-05 06:31:04] console.ERROR: Error thrown while running command "'make:user'". Message: "There are no commands defined in the "make" namespace.  You may be looking for a command provided by the "MakerBundle" which is currently not installed. Try running "composer require symfony/maker-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\". at /var/www/symfony/vendor/symfony/framework-bundle/EventListener/SuggestMissingPackageSubscriber.php:74)","command":"'make:user'","message":"There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\"."} []
[2019-10-05 06:52:15] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8000/api/login_check","method":"POST"} []
[2019-10-05 06:52:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-10-05 06:52:24] request.INFO: Matched route "app_api_login_checklogin". {"route":"app_api_login_checklogin","route_parameters":{"_route":"app_api_login_checklogin","_controller":"App\\Controller\\Api\\LoginController::checkLogin"},"request_uri":"http://localhost:8000/api/login_check","method":"POST"} []
[2019-10-05 06:52:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
